services:
  go: &go
    env_file: .env
    tty: true
    stdin_open: true
    build:
      context: .
    entrypoint: go
    command: help
    volumes:
      - .:/usr/src/app:delegated
      - gomod:/go/pkg/mod
      - ${LOCAL_DEP_PATH:-..}:/local

  app:
    <<: *go
    command: run ./server.go
    ports:
      - ${PORT}:${PORT}

  gen:
    <<: *go
    command: run github.com/99designs/gqlgen

volumes:
  gomod: {}
