// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Technology struct {
	ID       string  `json:"id"`
	Text     string  `json:"text"`
	PhotoURL *string `json:"photo_url"`
}

func (Technology) IsEntity() {}
